### ISSUE TITLE
Weird behaviour of dill in django

### ISSUE THREAD

**Issue by auuron** [uqfoundation/dill#146]
Hello, i had some issues with caching objects in django (because they were not pickleable) and decided to use dill.

The weird thing is that, when I import dill, issue disappears, like pickle was replaced by dill and i don't have to use dumps/loads. Is that correct behaviour?

**Comment by mmckerns** [comment]
when you `>>> import dill`, then everything `dill` knows how to pickle is added to the `pickle` registry.  So, yes, that's the expected behavior.  `dill` tells `pickle` how to handle most objects, and you don't have to do anything else.  To toggle this behavior explicitly, you can use `dill.extend(True)` or `False`.

**Comment by auuron** [comment]
thanks for answer!
