### ISSUE TITLE
Speed issues vs cPickle

### ISSUE THREAD

**Issue by MaximilianR** [uqfoundation/dill#149]
Should dill take 9x as much time as cPickle here? Is there anything we can do on our end to speed this up?

Thanks!

```python
obj=['{}'.format(n) for n in range(50000)]
obj

import dill
%timeit len(dill.dumps(obj))
#100 loops, best of 3: 233 ms per loop

import cPickle
%timeit len(cPickle.dumps(obj))
#1000 loops, best of 3: 26.3 ms per loop
```

**Comment by mmckerns** [comment]
I think you'll find in the majority of cases, `dill` is slower than `cPickle`.  The intent of `dill` is robustness of serialization of objects, as opposed to speed.  However, anything that can be done to speed it up is welcome, as long as it doesn't reduce the range of objects that can be serialized.  For example, one could add capacity to defer to `cPickle` if the object can be serialized with `cPickle`, and use `dill` otherwise.  I just recently greatly reduced the import time for `dill`, and similarly I'm sure there are other speed optimizations that could be made.  That hasn't been my focus to date, so there should be a good bit of room for improvement.

**Comment by MaximilianR** [comment]
OK, thanks. 
FWIW I remember when we were comparing speeds a year ago, our research suggested dill was materially faster in some areas.

**Comment by mmckerns** [comment]
If you do find any objects that are seriously slower, let us know.  I would like to have `dill` roughly as fast as `cPickle` in all cases.

**Comment by mmckerns** [comment]
Feel free to post any continued discussion here that may warrant reopening.
