### ISSUE TITLE
TypeError: ord() expected a character, but string of length 0 found (on Windows)

### ISSUE THREAD

**Issue by bmer** [uqfoundation/dill#158]
Hi all,

Some versioning info right away:

- Windows 10 Pro, 64bit

- `numba`: 0.22.1

- `numpy`: 1.10.4

- `dill`: 0.2.6.dev0

Having an issue with the following minimal working example, composed of two files. The first is `test.py`:

```
#test.py
import numba as nb
import numpy as np

class Ball():
    def __init__(self, name):
        self.name = name
        self.x = np.random.rand(10)
        
@nb.jit(nopython=True)
def my_fast_vector_add(x, y):
    num_elements = x.shape[0]
    z = np.zeros(num_elements, dtype=np.float64)
    
    for i in range(num_elements):
        z[i] = x[i] + y[i]

    return z  
      
class Environment():
    def __init__(self):
        self.x = np.random.rand(10)
        self.y = np.random.rand(10)
        self.ball = Ball("hello")
    
    def my_vector_add(self):
        return my_fast_vector_add(self.x, self.y)
```

...and the second is `doit.py`:

```
#doit.py
import test
import dill as pickling_package
import os
import shutil
import gzip

env = test.Environment()
print "init add result: ", env.my_vector_add()
pkl_path = "test.pkl"

with open(pkl_path, 'w') as f:
    pickling_package.dump(env, f)
    
compressed_path = "test.zip"
    
with open(pkl_path, 'r') as f_in, gzip.open(compressed_path, 'w') as f_out:
    shutil.copyfileobj(f_in, f_out)
                
os.remove(pkl_path)

stored_env = None
with gzip.open(compressed_path, 'r') as f_in:
    stored_env = pickling_package.load(f_in)
    print "loaded add result: ", stored_env.my_vector_add()
```

The following error is produced when running `doit.py`:

```

  File "A:/dill_issue/doit.py", line 26, in <module>
    stored_env = pickling_package.load(f_in)
  File "C:\Users\Brian\AppData\Roaming\Python\Python27\site-packages\dill\dill.py", line 250, in load
    obj = pik.load()
  File "A:\anaconda\lib\pickle.py", line 864, in load
    dispatch[key](self)
  File "A:\anaconda\lib\pickle.py", line 1175, in load_binput
    i = ord(self.read(1))
TypeError: ord() expected a character, but string of length 0 found
```

Any ideas what might be going on?

**Comment by mmckerns** [comment]
Your code works for me on a `MacOSX`.  I think the error you are seeing is because Windows expects binary mode… so replace `'w'` with `'wb'` and `'r'` with `'rb'` for the file modes in your `open` calls.

See this ancient bug submission: https://mail.python.org/pipermail/python-bugs-list/2005-April/028565.html

Let me know if that fixes it for you.

**Comment by mmckerns** [comment]
I'm going to assume this is now ok.  feel free to reopen if you are still having an issue.

**Comment by aliabbasjp** [comment]
objects containing pandas dataframe throw RuntimeError: maximum recursion depth exceeded

**Comment by mmckerns** [comment]
@aliabbasjp: if this is related to the current (closed) issue, then please provide more detail here.  Otherwise, please open a new issue, and provide details including code that can be reproduced.  In my experience, `pandas.DataFrames` will pickle with `dill` just fine, as I just checked with the latest `dill` and with latest `pandas`, so if you indeed are having difficulty as you say, please open an new issue.

**Comment by lrq3000** [comment]
This fixed my issue, thanks a lot @mmckerns !
