### ISSUE TITLE
TypeError: __init__() takes at least 3 arguments (2 given)

### ISSUE THREAD

**Issue by lucasrodes** [uqfoundation/dill#168]
I am working with NLTK and I need to store a dictionary containing lambda variables. Hence, I ended up with this library, which I did not know until now. To store the dictionary, I use `dill.dump( lm, open( 'testing', 'wb' ) )`, which seems to work fine. However I am having problems trying to load the stored file. Based on the recommendations from the official page of [pathos](http://trac.mystic.cacr.caltech.edu/project/pathos/wiki/dill) I am acting as if I was using the pickle library, that is using the same nomenclature as in the [pickle library](https://docs.python.org/2/library/pickle.html). However, it seems not to work at all. 

```
>>> pythdill.load(open('testing', 'rb'))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/veu4/usuaris30/speech00/.local/lib/python2.7/site-packages/dill/dill.py", line 250, in load
    obj = pik.load()
  File "/usr/lib64/python2.7/pickle.py", line 858, in load
    dispatch[key](self)
  File "/usr/lib64/python2.7/pickle.py", line 1133, in load_reduce
    value = func(*args)
TypeError: __init__() takes at least 3 arguments (2 given)
```

'`testing`' is the name of the file to load (located in the same directory).

Any ideas? Apreciate your time

PS: I am running Python 2.7.3 on GNU/Linux

**Comment by mmckerns** [comment]
Sorry I somehow missed this issue.  Let me know if you still are having problems with this and it needs to reopen.  Essentially, if you report an issue like this, you should provide both some minimal code that produces the error, and the traceback.  Since, I don't have the code you used, I can't reproduce your error, and thus can't give you any feedback.  I tried creating a `dict` of lambda variables and then doing a `dump` and `load`, and it worked for me.  If you still are getting this error, please reopen this ticket and post your code with the traceback here.

Note, I'd suggest using `with` for handling the files for the `dump` and `load`:
```
>>> with open('test.pkl', 'wb') as f:
...   dill.dump(lm, f)
... 
>>> with open('test.pkl', 'rb') as f:
...   lm_ = dill.load(f)
... 
>>>
```
