### ISSUE TITLE
re: spicy.spatial.cKDTree on RHEL 5.11 not being loaded properly

### ISSUE THREAD

**Issue by jGaboardi** [uqfoundation/dill#174]
I need to use Python 2.7.x to serialize `scipy.spatial.cKDTree` on an older version of RedHat. I can use `dill` to dump and load basic data structures in a session, but when loading a more exotic data structure like a`scipy.spatial.cKDTree` it is empty (see error message below).  Is this a known issue and is there a solution?  I am able to do this without error on `Python 2.7.11 Anaconda custom (x86_64)` in `OSX 10.11.5`.

System Specs-->
system: `RedHat Enterprise Server 5.11 Tikanga`
python: `Python 2.7.9 Anaconda 2.2.0 (64-bit)`

Error-->

```
Traceback (most recent call last):
  File "dill_cKD.py", line 75, in <module>
    print first_kdt.query(first_hh_coords, 4, distance_upper_bound=0.001)[1][:5]
  File "ckdtree.pyx", line 1213, in scipy.spatial.ckdtree.cKDTree.query (scipy/spatial/ckdtree.c:10537)
ValueError: x must consist of vectors of length 0 but has shape (125, 2)
```

`first_kdt.data.shape` should be `(125,2)` but it is loaded back as `NoneType`

```
In [5]: first_kdt.data.shape
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-5-5fee0823c0cc> in <module>()
----> 1 first_kdt.data.shape

AttributeError: 'NoneType' object has no attribute 'shape'
```

Thanks for any help or suggestions.

Best Regards,
James Gaboardi

**Comment by mmckerns** [comment]
Sorry for the neglect...  Is this still an issue?  If so, can you submit some code that demonstrates what you are seeing?  I just tried to make a `cKDtree` instance, with the most recent `dill` and `scipy`, and it works:
```
>>> import scipy.spatial
>>> import numpy
>>> import dill
>>> k = scipy.spatial.cKDTree(numpy.random.randint(10,size=(10,10)))
>>> _k = dill.copy(k)
>>> _k.data
array([[ 8.,  4.,  6.,  5.,  8.,  1.,  3.,  0.,  8.,  8.],
       [ 2.,  3.,  2.,  3.,  6.,  5.,  5.,  9.,  7.,  2.],
       [ 6.,  3.,  5.,  2.,  6.,  0.,  9.,  8.,  7.,  3.],
       [ 5.,  6.,  8.,  7.,  4.,  3.,  1.,  7.,  8.,  1.],
       [ 2.,  9.,  4.,  9.,  3.,  8.,  5.,  4.,  9.,  2.],
       [ 3.,  1.,  9.,  9.,  4.,  8.,  7.,  7.,  6.,  3.],
       [ 0.,  6.,  6.,  6.,  7.,  4.,  3.,  7.,  3.,  1.],
       [ 4.,  0.,  2.,  6.,  7.,  1.,  8.,  8.,  8.,  1.],
       [ 7.,  0.,  0.,  3.,  9.,  5.,  9.,  0.,  3.,  2.],
       [ 5.,  2.,  2.,  0.,  5.,  7.,  4.,  2.,  1.,  2.]])
```

Note that there have been improvements to picking of `numpy` and `scipy` data structures since versions current around the time of python `2.7.9`.  So I expect the best option would be to install a more recent version of your dependencies.  You can often do a "user" (or "home") install if you don't have root on your target system.  I often do exactly that.  You'll probably have to edit the `$PATH`, but it's not terrible to do so.

**Comment by mmckerns** [comment]
I should note that `copy(k)` is just `loads(dumps(k))`.

Also, it's going to be difficult to reproduce your platform/system combination, and since you didn't provide code + traceback, there's not much else that can be done here.  My best suggestion is to do a "user" install that utilizes more recent versions of everything.  As you can see, the combination of the most recent versions of everything seem to work just fine.

Please reopen this ticket if you have additional input.
