### ISSUE TITLE
Add a changelog to the project

### ISSUE THREAD

**Issue by alexkiro** [uqfoundation/dill#223]
Would be possible to add a changelog file to the project? E.g I wanted to update to the latest version, but there are quite a lot of [changes](https://github.com/uqfoundation/dill/compare/dill-0.2.5...0.2.6). So I'm not sure what's new.

**Comment by mmckerns** [comment]
I understand the request... I use something like this: https://github.com/uqfoundation/dill/compare/0.2.6...dill-0.2.7, which is exactly what you have done in your post.  I also maintain a milestone for each release that associates all closed tickets for that release (notably, I haven't been tagging the closed PRs with the milestone, but I will start doing that).

I mean, if I made a changeling...  I'd just list what shows up in the commit logs and also would list the tickets and PRs that are closed.   Do you know of a good way to automatically generate a changelog that would give something different that the three things I'm referencing above?

**Comment by aaltay** [comment]
To +1 on this request, it would be good to get a list of curated release notes. For example, I am particularly interested in knowing why dill version changed from 0.2.9 to 0.3.0. Is it because some breaking change happened in between? Release notes could answer questions like this.

For context, I would like to understand whether https://github.com/apache/beam should upgrade to the latest dill version and what would need to change if anythin in Beam in order to do that.

**Comment by SuperSandro2000** [comment]
Currently the changelog section in the github releases is filled with a static template which is not helpful wenn upgrading dependencies.

**Comment by mmckerns** [comment]
I could add a link to this page... https://github.com/uqfoundation/dill/compare/dill-0.3.5.1...dill-0.3.6

**Comment by SuperSandro2000** [comment]
There is a compare button on the left of the releases page which gets me there, too but I still don't know if this is a very minor update or has major breaking changes I need to consider.

**Comment by sandrotosi** [comment]
> Currently the changelog section in the github releases is filled with a static template which is not helpful wenn upgrading dependencies.

this please, i was trying to figure out which version started supported officially py3.11 and noticed that all releases text is simple boilerplate.

Releases are (in contrast to pure git tags) a way the developers can communicate what has changed when "releasing" a new version, lets take advantage of that

thanks!

**Comment by mmckerns** [comment]
@sandrotosi: Maybe the reason you couldn't find which release `dill` officially started supporting python 3.11 is that the answer is "None".

The latest release officially supports python up to and including 3.10 -- although python 3.11 should work with the latest release, 3.11.0 wasn't yet released when we released `dill-0.3.6` so it couldn't be formally supported at the time. If you wanted to find out which commit added official support for 3.11, you can go to the `dill-0.3.6` release page and instead of clicking the "compare" button, click "... commits to master since this release": https://github.com/uqfoundation/dill/compare/dill-0.3.6...master, and you will see a commit that states it "formally supports" 3.11 (and a commit that adds support for 3.12, starting the 'informal' support for 3.12). You can see all the commit information comparing between two releases and to master very easily by going to the latest release page.

**Comment by sandrotosi** [comment]
> @sandrotosi: Maybe the reason you couldn't find which release `dill` officially started supporting python 3.11 is that the answer is "None".

which i would have notice as missing in the release notes.
Anyhow, i went ahead and package dill for debian with python3.11 and all appears to be working fine.

> The latest release officially supports python up to and including 3.10 -- although python 3.11 should work with the latest release, 3.11.0 wasn't yet released when we released `dill-0.3.6` so it couldn't be formally supported at the time. If you wanted to find out which commit added official support for 3.11, you can go to the `dill-0.3.6` release page and instead of clicking the "compare" button, click "... commits to master since this release": [dill-0.3.6...master](https://github.com/uqfoundation/dill/compare/dill-0.3.6...master), and you will see a commit that states it "formally supports" 3.11 (and a commit that adds support for 3.12, starting the 'informal' support for 3.12). You can see all the commit information comparing between two releases and to master very easily by going to the latest release page.

thanks for going thru this, but i think that suggesting users to git diff, instead of publishing a detailed changelog and release notes is suboptimal, and other people in this issue seem to think the same.

thanks for considering enhancing your release process to support our use case, we know it's grunt work but it'll be appreciated :)

**Comment by mmckerns** [comment]
A new release is coming out shortly. Github now provide a "generate release notes" button, which includes the `diff` between the current and prior release. I'll generate and post the autogenerated release notes as part of the release process.

**Comment by mmckerns** [comment]
done
