### ISSUE TITLE
Issue with deserializing on Windows

### ISSUE THREAD

**Issue by P-Andersson** [uqfoundation/dill#230]
I have an issue with deserializing something on Windows 10, but it runs perfectly well on Ubuntu. I serialize a function, along with some arguments that while they may carry quite a bit of state with them it should only be classes with simple types; aside from some function references. 

The error I get when I try to deserialize is the following:

```
Traceback (most recent call last):
  File "C:\rcs\BaseTestShellRdk\.rdk\local_rdk\scripts\new_terminal_start.py", l
ine 57, in <module>
    sys.exit(main())
  File "C:\rcs\BaseTestShellRdk\.rdk\local_rdk\scripts\new_terminal_start.py", l
ine 43, in main
    f = dill.load(f_file)
  File "C:\Python27\lib\site-packages\dill-0.2.6-py2.7.egg\dill\dill.py", line 2
66, in load
    obj = pik.load()
  File "C:\Python27\lib\pickle.py", line 864, in load
    dispatch[key](self)
  File "C:\Python27\lib\pickle.py", line 1195, in load_appends
    list.extend(stack[mark + 1:])
AttributeError: type object 'code' has no attribute 'extend'

```

Is there a known issue or potentially some type that are known to cause this problem that I  could look for?

**Comment by mmckerns** [comment]
@P-Andersson: User-defined classes can be pretty tricky, so it's totally possible that this is either a known failure, or an unknown one.  Can you provide code for a minimal test case that I can run and reproduce your error?   Yes, there are a few case (you can look at the other issues) where an object pickles on non-windows systems and fails on windows... as well as serialization failures being caused by certain objects being used in the class, or sometimes just being in `globals`.

If you post some code, please also provide your version of `dill` you are using, and any other identifying information that can help me reproduce what you are seeing.

**Comment by P-Andersson** [comment]
@mmckerns after some debugging, I found the cause. I was opening the files storing the serialization data with open(file) instead of open(file, 'rb'). Which could cause problems on windows!

**Comment by mmckerns** [comment]
Indeed that would.  Well... great that you solved it  Let me know if you run into anything else.
