### ISSUE TITLE
Question: Compatibility between different dill versions?

### ISSUE THREAD

**Issue by ddebrunner** [uqfoundation/dill#270]
Does dill provide any guarantees about compatibility between different versions? E.g serialize with `0.2.8.2` and deserialize with `0.2.7.1`? Or a way to set compatibility when one can't control one of the (or both) systems where serialization and deserialization will occur?

I couldn't see anything in the documentation covering compatibility.

**Comment by mmckerns** [comment]
@ddebrunner: We make every attempt to ensure compatibility across all versions of `dill`.  There's a test suite that is tested on every checkin, and is used to ensure that the results don't change.  I do not like to accept changes that break backward compatibility, and have noted any time that has happened.  It's very very very few times over the course of 10+ years (I can think of only once it was done intentionally).  That being said, we just broke it across versions of `dill` unintentionally.  Mostly because we didn't think of testing the particular case that was broken by the change.  Had we thought of it, we'd have avoided the break (instead of rectifying it with a patch release).  We don't test have a test against different flavors of old pickles. We could, but we don't at the moment.  We are very conscious of breaking backward compatibility, however, and will not intentionally do it.

**Comment by mmckerns** [comment]
If you have an example + traceback of any particular break, please post it, and we will see what we can do to rectify.

**Comment by mmckerns** [comment]
As noted in your above-referenced issue, it seems that your are using an essentially "non-public" interface... `dill._dill._reverse_typemap`.  So, if you are looking for a guarantee, there is none when using an interface that is not intended to be used.  Even saying that, I can think of only once that any interface to `dill` was changed in a backward incompatible way.  I'm assuming this answers your question, so please reopen if this doesn't.

**Comment by ddebrunner** [comment]
@mmckerns This issue wasn't related to `dill._dill._reverse_typemap`.

>We make every attempt to ensure compatibility across all versions of dill.

Just to be clear, are you saying that if I serialize an object using dill `0.2.8.2` older versions of dill can continue to deserialize it. I'm more trying to get a statement of what is expected to be supported.

**Comment by mmckerns** [comment]
Yes.

**Comment by ddebrunner** [comment]
@mmckerns I opened an issue #272 with a simple repo.

**Comment by mmckerns** [comment]
I'm closing this issue, as it seems I've answered your question here.
