### ISSUE TITLE
Dill is slow

### ISSUE THREAD

**Issue by horpto** [uqfoundation/dill#292]
Hi, I wanna try to use dill to speed up some multiprocessing stuff as pickle is slow. But dill even is slower than pickle!

```
import dill
import time

data = [(i, i+1, i+2, i+3) for i in range(10**6)]
print('Start!')
t_start = time.time()
pickle_data = dill.dumps(data)
print("dill test: dumps took %s seconds" % (time.time() - t_start))

t_start = time.time()
dill.loads(pickle_data)
print("dill test: loads took %s seconds" % (time.time()-t_start))
```

It tooks 

> dill test: dumps took 49.03148174285889 seconds
> dill test: loads took 6.416576623916626 seconds

It's very slow! Pickle tooks 2.72 and 1.98 s.

Python 3.7.1
dill 0.2.8.2
Windows 8.1

**Comment by mmckerns** [comment]
Also, `pickle` generally pickles by reference, while `dill` does not -- `dill` serializes much more than `pickle` because it explicitly converts more objects to pickled strings.  The point would be that you actually *can* do multiprocessing with certain objects... instead of getting errors, as you would get with `pickle`.  FYI, if are looking to use `dill` for `multiprocessing`, have a look at `multiprocess` -- a fork of `multiprocessing` that is fully integrated with `dill`.

Please reopen this ticket if you have further comments or questions with regard to the above.
