### ISSUE TITLE
Cannot pickle dict_items, dict_keys & dict_values on Python-3

### ISSUE THREAD

**Issue by ankostis** [uqfoundation/dill#353]
This simple code fails on Python3 9but on Python 2):
```python
dill.dumps({}.items())
```

It is a pretty common object in the python universe.
.

**Comment by mmckerns** [comment]
Huh... They actually fail to pickle on all versions of python 3.x.  I'm surprised I wasn't aware of this.

**Comment by eldipa** [comment]
Would make sense to add an optional pickler/unpickler functions for them, like serializing them to a `tuple`? This is what I'm implementing for a personal project, may be other would benefit from this.

I'm thinking in this as an optional feature just in case that the dict_values (and the others) are potentially huge; it's better to fail with a `can't pickle` instead of an out of memory.

Would you think that this could be integrated in `dill`?
