### ISSUE TITLE
restored np.nan is not np.nan

### ISSUE THREAD

**Issue by matanster** [uqfoundation/dill#515]
I encounter a case where a dill unpickled `numpy.nan` passes as a `numpy.isnan` but is contrary to expectation, _not_ a `np.nan`. 
Meaning that some dill pickled np.nan assigned variable (named below `v2`) makes `v2 is np.nan` evaluate to False after unpickling it with dill, as shown in the debug screenshot. 

Please excuse the mere screenshot elucidation of the matter, and I will follow up with minimally reproducible code.

![image](https://user-images.githubusercontent.com/4996067/174461231-b83648e4-5d96-498b-ad02-c327ac465f9b.png)

I wonder if this corresponds to some known issue or limitation.

# version info
dill: 0.3.5.1
numpy: 1.22.4
python: 3.9.5
OS: Ubuntu 20.04

# Workaround
I could work around it by making sure I have `None` rather than `np.nan` values in my numpy arrays (and using `is None` accordingly).

**Comment by anivegesana** [comment]
I believe that this is consistent with how Python ints and floats behave. Converting them to a string and converting them back or pickling them and pickling them is not necessarily guaranteed to yield the same object. Just use `math.isnan` or `np.isnan` to check for nan-ness both when using the standard `math` package and `numpy` as well as using `==` instead of `is` whenever you are comparing objects that are not guaranteed to be unique.

```py
>>> import math
>>> float(str(math.nan)) is math.nan
False
>>> math.isnan(float(str(math.nan)))
True
>>> float(str(9)) is 9
<stdin>:1: SyntaxWarning: "is" with a literal. Did you mean "=="?
False
>>> float(str(9)) == 9
True
>>> import pickle
>>> pickle.loads(pickle.dumps(9000)) is 9000
<stdin>:1: SyntaxWarning: "is" with a literal. Did you mean "=="?
False
>>> pickle.loads(pickle.dumps(9.0)) is 9.0
<stdin>:1: SyntaxWarning: "is" with a literal. Did you mean "=="?
False
```

**Comment by mmckerns** [comment]
Thanks for reporting.  I'm going to close this issue. Please reopen if there's more to address here.

**Comment by matanster** [comment]
I can't say I entirely grok how python doesn't provide a stable `nan` facade surviving serialization and de-serialization, but the issue is clear now and I'm closing it. Thanks for bringing these details to my attention!

**Comment by anivegesana** [comment]
Python doesn't even have stable reconstruction of most floats and ints. There is a cache of small integer objects that will yield the same object the every time for efficiency.

Python is hardly alone here. The same applies to boxed primitives in Java, [Cool](https://github.com/soulporpoise/coolc/blob/f906e7694537c6faaa1f3279586f8f9c3588bdee/pa4/cgen.cc#L1454) (the easiest OO language to play around with and see exactly why this limitation exists,) and any other language that is truly object oriented with nonprimitive numerical types. The issue is that it is not possible to remember and efficiently index all existing numerical objectives in order to find one that exists and has the same value. An algorithm would be either too inefficient in time or space for programs that use lots of numerical objects. It is just easier to lump nan in with every other float in this regard instead or carving out a specific requirement for only one nan object to exist.

**Comment by matanster** [comment]
> Python doesn't even have stable reconstruction of most floats and ints. There is a cache of small integer objects that will yield the same object the every time for efficiency.

That's a bit beyond me, perhaps you might be able to recommend some reading or terminology I could look up on this aspect, and thanks again for the comments!

**Comment by anivegesana** [comment]
This is all related to the design of programming languages. These choices are made to make the best tradeoff between maintainability and efficiency. If you are interested in that sort of stuff in general, you can look up lecture notes for compiler, program optimization, and programming language design courses at universities.

For the more specific instance that you asked about, there is only a single line buried in the Python documentation discussing the integer cache: https://docs.python.org/3.8/c-api/long.html#c.PyLong_FromLong

I specifically chose 9000 for the integer that I was generating a copy of instead of 9 so it would fall outside of this cache:
```pycon
>>> int(str(9)) is 9
True
```

In addition to small integers, booleans (`True` and `False`), the singletons (`None`, `NotImplemented`, and `...`), and enums (through overloading the `__new__` function to not create new objects instead of anything specific in the interpreter) are guaranteed to be unique.

Overall, these details are not too important for the average programmer. It is idiomatic to use `is` for singletons and enums. For booleans, just use the direct value without comparison. For nan comparisons, use `isnan`. In every other scenario, using `==` instead of `is` is used. This style convention is outlined in [PEP 8](https://peps.python.org/pep-0008/), is sufficient for avoiding bugs related to checking equality, and modern versions of Python will issue a warning if you break those rules in most cases. There is no real reason to look into it more unless you are curious about what is going on under the hood.
