### ISSUE TITLE
Problem with loading metaclasses

### ISSUE THREAD

**Issue by h4nsu** [uqfoundation/dill#88]
I recently started using dill instead of pickle in my project and it's really great. However I ran into some problem. I have the following code:

test.py:
```python
import dill

class Meta(type): pass

class A(object):
    __metaclass__ = Meta

b = A()
with open('somefile', 'wb') as f:
    dill.dump(b,f)
```

Now I execute it with `python2 test.py`, it creates `somefile` and everything is fine. But when I open the interpreter and try `b = dill.load(open('somefile'))` I get the following error:

    AttributeError                            Traceback (most recent call last)
    <ipython-input-1-4fc5ba18542c> in <module>()
    ----> 1 j = pickle.load(open('somefile'))

    /usr/lib/python2.7/site-packages/dill-0.2.2-py2.7.egg/dill/dill.pyc in load(file)
        197     pik = Unpickler(file)
        198     pik._main_module = _main_module
    --> 199     obj = pik.load()
        200     if type(obj).__module__ == _main_module.__name__: # point obj class to main
        201         try: obj.__class__ == getattr(pik._main_module, type(obj).__name__)

    /usr/lib/python2.7/pickle.pyc in load(self)
        856             while 1:
        857                 key = read(1)
    --> 858                 dispatch[key](self)
        859         except _Stop, stopinst:
        860             return stopinst.value

    /usr/lib/python2.7/pickle.pyc in load_global(self)
       1088         module = self.readline()[:-1]
       1089         name = self.readline()[:-1]
    -> 1090         klass = self.find_class(module, name)
       1091         self.append(klass)
       1092     dispatch[GLOBAL] = load_global

    /usr/lib/python2.7/site-packages/dill-0.2.2-py2.7.egg/dill/dill.pyc in find_class(self, module, name)
        276         if (module, name) == ('__builtin__', '__main__'):
        277             return self._main_module.__dict__ #XXX: above set w/save_module_dict
    --> 278         return StockUnpickler.find_class(self, module, name)
        279     pass
        280 

    /usr/lib/python2.7/pickle.pyc in find_class(self, module, name)
       1124         __import__(module)
       1125         mod = sys.modules[module]
    -> 1126         klass = getattr(mod, name)
       1127         return klass
       1128 

    AttributeError: 'module' object has no attribute 'A'

If I remove `__metaclass__` from class definition, everything works fine. The default `pickle` module had problems with loading instances of classes without knowing (explicitly importing) the class definition. `dill` can do this, but apparently only for classes that do not use metaclasses. Is there any reason why is it that way? Does any solution or workaround to this problem exist?

**Comment by matsjoyce** [comment]
Good catch, its reproducible in python 3 with `class A(metaclass=Meta):`. The problem is that since `type(A)` is `Meta`, not `type`, all the dill serialisation (no output from `_trace`) is skipped, so pickle does all the work, and, as it is in `__main__`, cannot handle it. Since this sort of how pickle is supposed to work, we'll somehow have to hijack a bit deeper than normal.

**Comment by matsjoyce** [comment]
[This how metaclasses are handled by pickle](https://github.com/python/cpython/blob/master/Lib/pickle.py#L483-L490):

```py
# Check for a class with a custom metaclass; treat as regular class
try:
    issc = issubclass(t, type)
except TypeError: # t is not a class (old Boost; see SF #502085)
    issc = False
if issc:
    self.save_global(obj)
    return
```
Unfortunately, the way `dill` gets in the way is 10 lines above, and it searches based on class, which in this case is unique. I can see to ways of solving this:

 - Make `Pickler.dispatch` a `dict`-subclass, so that we can intercept searches for `type` subclasses and deal out the correct function.
 - Override `Pickler.save_global` and deal out the correct function.

I think the first one is slightly easier, but they are both hackish. This is probably a big enough use-case for a good fix, though.

**Comment by mmckerns** [comment]
Nice find @h4nsu.  @matsjoyce: Are there any unique attributes of a class that uses metaclasses?  If we can use that as a flag, we can pick them off the registered `dispatch` for `type` and ship the objects to the right pickling/unpickling function.

**Comment by matsjoyce** [comment]
@mmckerns I've tried implementing method one at https://github.com/matsjoyce/dill/tree/metaclasses, and it seems to work. Shall I PR it?

**Comment by mmckerns** [comment]
@matsjoyce: yes. it looks like a pretty nice solution

**Comment by mmckerns** [comment]
looks fixed. Thanks @matsjoyce
